SELECT 
    c.ID,
    c.GENOTYPE,
    p.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA c
JOIN ECOLI_DATA p 
    ON c.PARENT_ID = p.ID
WHERE (c.GENOTYPE & p.GENOTYPE) = p.GENOTYPE # 부모 형질을 모두 포함하는 자식만 걸러내기 
ORDER BY c.ID;