SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D JOIN SKILLCODES S ON D.SKILL_CODE & S.CODE = S.CODE
WHERE S.NAME IN ('Python', 'C#')
ORDER BY D.ID;

SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM  DEVELOPERS D JOIN SKILLCODES S  ON D.SKILL_CODE & S.CODE = S.CODE
WHERE S.NAME IN ('Python', 'C#')
ORDER BY D.ID;


SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM SKILLCODES S, DEVELOPERS D
WHERE S.CODE & S.CODE > 0
  AND S.NAME IN ('Python', 'C#')
ORDER BY D.ID;


SELECT DISTINCT d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME
FROM DEVELOPERS d JOIN SKILLCODES s ON d.SKILL_CODE & s.CODE = s.CODE
WHERE s.NAME IN ('Python', 'C#')
ORDER BY d.ID;